In [1]:
import pandas as pd
df = pd.read_csv('C:/Users/gupta/Downloads/Master_Mine_Operations.csv')

In [2]:
df.head()

,Production ID,Date,Shift,Bench ID,Pit,Equipment ID,Equipment Type,Employee ID,Employee Role,Ore_Tonnes,...,Breakdown Hours,Repair Cost,Weather,Temperature_C,Blast ID,Hole Depth_m,Powder Factor,Incident Type,Severity,Lost Days
0,P00001,2025-01-01,C,B017,North Pit,EQ221,Dozer,EMP0143,Mining Engineer,2234,...,0,78332,Clear,20.0,BL05026,9.4,0.77,Near Miss,High,6
1,P00002,2025-01-02,A,B014,South Pit,EQ222,Dumper,EMP0412,Mining Engineer,1928,...,0,0,Fog,22.8,BL05064,12.7,0.78,NaN,NaN,0
2,P00003,2025-01-03,A,B091,North Pit,EQ160,Drill,EMP0222,Mechanic,3398,...,5,40548,Clear,30.2,BL03538,11.4,1.06,Near Miss,Low,0
3,P00004,2025-01-04,B,B081,North Pit,EQ201,Drill,EMP0253,Mechanic,3854,...,0,0,Cloudy,35.3,BL04947,12.4,1.06,Minor Injury,Medium,2
4,P00005,2025-01-05,B,B010,North Pit,EQ031,Loader,EMP0224,Mining Engineer,1241,...,0,28914,Rain,28.5,BL02911,13.6,0.77,Unsafe Act,Low,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Production ID     12000 non-null  object
 1   Date              12000 non-null  object
 2   Shift             12000 non-null  object
 3   Bench ID          12000 non-null  object
 4   Pit               12000 non-null  object
 5   Equipment ID      12000 non-null  object
 6   Equipment Type    12000 non-null  object
 7   Employee ID       12000 non-null  object
 8   Employee Role     12000 non-null  object
 9   Ore_Tonnes        12000 non-null  int64
 10  Waste_Tonnes      12000 non-null  int64
 11  Target_Tonnes     12000 non-null  int64
 12  Actual_Tonnes     12000 non-null  int64
 13  Fuel_Litres       12000 non-null  int64
 14  Fuel Cost         12000 non-null  int64
 15  Maintenance Type  8118 non-null   object
 16  Breakdown Hours   12000 non-null  int64
 17  Repair Cost       12000 non-null  int64
 18  Weather           12000 non-null  object
 19  Temperature_C     12000 non-null  float64
 20  Blast ID          12000 non-null  object
 21  Hole Depth_m      12000 non-null  float64
 22  Powder Factor     12000 non-null  float64
 23  Incident Type     9014 non-null   object
 24  Severity          9014 non-null   object
 25  Lost Days         12000 non-null  int64
dtypes: float64(3), int64(9), object(14)
memory usage: 2.4+ MB

In [4]:
df.describe(include='all')

,Production ID,Date,Shift,Bench ID,Pit,Equipment ID,Equipment Type,Employee ID,Employee Role,Ore_Tonnes,...,Breakdown Hours,Repair Cost,Weather,Temperature_C,Blast ID,Hole Depth_m,Powder Factor,Incident Type,Severity,Lost Days
count,12000,12000,12000,12000,12000,12000,12000,12000,12000,12000.000000,...,12000.000000,12000.00000,12000,12000.000000,12000,12000.00000,12000.000000,9014,9014,12000.000000
unique,12000,365,3,100,2,250,5,600,4,NaN,...,NaN,NaN,4,NaN,5206,NaN,NaN,3,3,NaN
top,P00001,2025-01-01,B,B033,South Pit,EQ185,Excavator,EMP0128,Operator,NaN,...,NaN,NaN,Fog,NaN,BL01558,NaN,NaN,Unsafe Act,Low,NaN
freq,1,33,4047,145,6003,70,2453,35,3034,NaN,...,NaN,NaN,3078,NaN,11,NaN,NaN,3066,3066,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2701.108167,...,1.861917,28512.69925,NaN,29.976617,NaN,11.04120,0.825684,NaN,NaN,1.969833
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,861.707501,...,3.096689,26640.88210,NaN,6.956501,NaN,1.73399,0.158927,NaN,NaN,2.437297
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.000000,...,0.000000,0.00000,NaN,18.000000,NaN,8.00000,0.550000,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1950.750000,...,0.000000,0.00000,NaN,23.900000,NaN,9.60000,0.690000,NaN,NaN,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2707.000000,...,0.000000,23820.50000,NaN,30.100000,NaN,11.10000,0.830000,NaN,NaN,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3446.000000,...,3.000000,51561.50000,NaN,36.000000,NaN,12.50000,0.960000,NaN,NaN,4.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4200.000000,...,10.000000,79998.00000,NaN,42.000000,NaN,14.00000,1.100000,NaN,NaN,7.000000

In [5]:
df.isnull().sum()

Production ID          0
Date                   0
Shift                  0
Bench ID               0
Pit                    0
Equipment ID           0
Equipment Type         0
Employee ID            0
Employee Role          0
Ore_Tonnes             0
Waste_Tonnes           0
Target_Tonnes          0
Actual_Tonnes          0
Fuel_Litres            0
Fuel Cost              0
Maintenance Type    3882
Breakdown Hours        0
Repair Cost            0
Weather                0
Temperature_C          0
Blast ID               0
Hole Depth_m           0
Powder Factor          0
Incident Type       2986
Severity            2986
Lost Days              0
dtype: int64

In [6]:
df["Maintenance Type"] = df["Maintenance Type"].fillna("No Maintenance")
df["Incident Type"] = df["Incident Type"].fillna("No Incident")
df["Severity"] = df["Severity"].fillna("None")

In [7]:
df.isnull().sum()

Production ID       0
Date                0
Shift               0
Bench ID            0
Pit                 0
Equipment ID        0
Equipment Type      0
Employee ID         0
Employee Role       0
Ore_Tonnes          0
Waste_Tonnes        0
Target_Tonnes       0
Actual_Tonnes       0
Fuel_Litres         0
Fuel Cost           0
Maintenance Type    0
Breakdown Hours     0
Repair Cost         0
Weather             0
Temperature_C       0
Blast ID            0
Hole Depth_m        0
Powder Factor       0
Incident Type       0
Severity            0
Lost Days           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Date"] = pd.to_datetime(df["Date"])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Production ID     12000 non-null  object
 1   Date              12000 non-null  datetime64[ns]
 2   Shift             12000 non-null  object
 3   Bench ID          12000 non-null  object
 4   Pit               12000 non-null  object
 5   Equipment ID      12000 non-null  object
 6   Equipment Type    12000 non-null  object
 7   Employee ID       12000 non-null  object
 8   Employee Role     12000 non-null  object
 9   Ore_Tonnes        12000 non-null  int64
 10  Waste_Tonnes      12000 non-null  int64
 11  Target_Tonnes     12000 non-null  int64
 12  Actual_Tonnes     12000 non-null  int64
 13  Fuel_Litres       12000 non-null  int64
 14  Fuel Cost         12000 non-null  int64
 15  Maintenance Type  12000 non-null  object
 16  Breakdown Hours   12000 non-null  int64
 17  Repair Cost       12000 non-null  int64
 18  Weather           12000 non-null  object
 19  Temperature_C     12000 non-null  float64
 20  Blast ID          12000 non-null  object
 21  Hole Depth_m      12000 non-null  float64
 22  Powder Factor     12000 non-null  float64
 23  Incident Type     12000 non-null  object
 24  Severity          12000 non-null  object
 25  Lost Days         12000 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(9), object(13)
memory usage: 2.4+ MB

In [11]:
df.columns =df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [12]:
df.head(10)

,production_id,date,shift,bench_id,pit,equipment_id,equipment_type,employee_id,employee_role,ore_tonnes,...,breakdown_hours,repair_cost,weather,temperature_c,blast_id,hole_depth_m,powder_factor,incident_type,severity,lost_days
0,P00001,2025-01-01,C,B017,North Pit,EQ221,Dozer,EMP0143,Mining Engineer,2234,...,0,78332,Clear,20.0,BL05026,9.4,0.77,Near Miss,High,6
1,P00002,2025-01-02,A,B014,South Pit,EQ222,Dumper,EMP0412,Mining Engineer,1928,...,0,0,Fog,22.8,BL05064,12.7,0.78,No Incident,None,0
2,P00003,2025-01-03,A,B091,North Pit,EQ160,Drill,EMP0222,Mechanic,3398,...,5,40548,Clear,30.2,BL03538,11.4,1.06,Near Miss,Low,0
3,P00004,2025-01-04,B,B081,North Pit,EQ201,Drill,EMP0253,Mechanic,3854,...,0,0,Cloudy,35.3,BL04947,12.4,1.06,Minor Injury,Medium,2
4,P00005,2025-01-05,B,B010,North Pit,EQ031,Loader,EMP0224,Mining Engineer,1241,...,0,28914,Rain,28.5,BL02911,13.6,0.77,Unsafe Act,Low,0
5,P00006,2025-01-06,C,B065,South Pit,EQ084,Dozer,EMP0417,Operator,2543,...,0,55999,Clear,37.3,BL04380,13.5,0.88,No Incident,None,0
6,P00007,2025-01-07,A,B051,South Pit,EQ240,Dozer,EMP0041,Supervisor,2829,...,3,31332,Fog,23.4,BL05005,10.5,0.91,Minor Injury,Low,0
7,P00008,2025-01-08,B,B088,North Pit,EQ191,Loader,EMP0230,Mechanic,1731,...,0,0,Rain,40.2,BL03653,9.9,0.84,Unsafe Act,Low,0
8,P00009,2025-01-09,B,B002,South Pit,EQ011,Dozer,EMP0415,Operator,3705,...,0,14657,Rain,33.2,BL00700,9.4,0.85,Minor Injury,Medium,6
9,P00010,2025-01-10,C,B041,South Pit,EQ104,Excavator,EMP0513,Operator,3549,...,0,0,Clear,40.0,BL04588,12.4,0.60,No Incident,None,0

In [13]:
df= df.rename(columns={'ore_tonnes' : 'ore_in_tonnes'})

In [14]:
df.columns

Index(['production_id', 'date', 'shift', 'bench_id', 'pit', 'equipment_id',
       'equipment_type', 'employee_id', 'employee_role', 'ore_in_tonnes',
       'waste_tonnes', 'target_tonnes', 'actual_tonnes', 'fuel_litres',
       'fuel_cost', 'maintenance_type', 'breakdown_hours', 'repair_cost',
       'weather', 'temperature_c', 'blast_id', 'hole_depth_m', 'powder_factor',
       'incident_type', 'severity', 'lost_days'],
      dtype='object')

In [15]:
df["production_id"].is_unique

True

In [16]:
df[df["ore_in_tonnes"] < 0]

Empty DataFrame
Columns: [production_id, date, shift, bench_id, pit, equipment_id, equipment_type, employee_id, employee_role, ore_in_tonnes, waste_tonnes, target_tonnes, actual_tonnes, fuel_litres, fuel_cost, maintenance_type, breakdown_hours, repair_cost, weather, temperature_c, blast_id, hole_depth_m, powder_factor, incident_type, severity, lost_days]
Index: []

[0 rows x 26 columns]

In [17]:
df[df["fuel_litres"] < 0]

Empty DataFrame
Columns: [production_id, date, shift, bench_id, pit, equipment_id, equipment_type, employee_id, employee_role, ore_in_tonnes, waste_tonnes, target_tonnes, actual_tonnes, fuel_litres, fuel_cost, maintenance_type, breakdown_hours, repair_cost, weather, temperature_c, blast_id, hole_depth_m, powder_factor, incident_type, severity, lost_days]
Index: []

[0 rows x 26 columns]

In [20]:
df[df["temperature_c"] < -10]

Empty DataFrame
Columns: [production_id, date, shift, bench_id, pit, equipment_id, equipment_type, employee_id, employee_role, ore_in_tonnes, waste_tonnes, target_tonnes, actual_tonnes, fuel_litres, fuel_cost, maintenance_type, breakdown_hours, repair_cost, weather, temperature_c, blast_id, hole_depth_m, powder_factor, incident_type, severity, lost_days]
Index: []

[0 rows x 26 columns]

In [21]:
df= df.rename(columns={'temperature_in_c' : 'temperature_c'})
df= df.rename(columns={'ore_in_tonnes' : 'ore_tonnes'})
df= df.rename(columns={'hole_depth_in_m' : 'hole_depth_m'})

In [22]:
df.columns

Index(['production_id', 'date', 'shift', 'bench_id', 'pit', 'equipment_id',
       'equipment_type', 'employee_id', 'employee_role', 'ore_tonnes',
       'waste_tonnes', 'target_tonnes', 'actual_tonnes', 'fuel_litres',
       'fuel_cost', 'maintenance_type', 'breakdown_hours', 'repair_cost',
       'weather', 'temperature_c', 'blast_id', 'hole_depth_m', 'powder_factor',
       'incident_type', 'severity', 'lost_days'],
      dtype='object')

In [23]:
df["total_material"] = (
    df["ore_tonnes"] +
    df["waste_tonnes"]
)

In [24]:
df[['production_id', 'total_material']].head(6)

  production_id  total_material
0        P00001            7264
1        P00002            7455
2        P00003            5975
3        P00004            6613
4        P00005            3466
5        P00006            5331

In [25]:
df["production_variance"] = (
    df["actual_tonnes"] -
    df["target_tonnes"]
)

In [26]:
df[['production_id', 'production_variance']].head(6)

  production_id  production_variance
0        P00001                   28
1        P00002                  -91
2        P00003                  238
3        P00004                  148
4        P00005                  300
5        P00006                 -163

In [27]:
df["achievement_%"] = (
    df["actual_tonnes"] /
    df["target_tonnes"]
) * 100

In [28]:
df[['production_id', 'achievement_%']].head(6)

  production_id  achievement_%
0        P00001     100.386954
1        P00002      98.794063
2        P00003     104.148510
3        P00004     102.289250
4        P00005     109.475679
5        P00006      97.033127

In [29]:
df["fuel_price"] = (
    df["fuel_cost"] /
    df["fuel_litres"]
)

In [30]:
df["month"] = df["date"].dt.month_name()
df["year"] = df["date"].dt.year
df["quarter"] = df["date"].dt.quarter
df["day"] = df["date"].dt.day_name()

In [31]:
#final check
df.info()

df.describe()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   production_id        12000 non-null  object
 1   date                 12000 non-null  datetime64[ns]
 2   shift                12000 non-null  object
 3   bench_id             12000 non-null  object
 4   pit                  12000 non-null  object
 5   equipment_id         12000 non-null  object
 6   equipment_type       12000 non-null  object
 7   employee_id          12000 non-null  object
 8   employee_role        12000 non-null  object
 9   ore_tonnes           12000 non-null  int64
 10  waste_tonnes         12000 non-null  int64
 11  target_tonnes        12000 non-null  int64
 12  actual_tonnes        12000 non-null  int64
 13  fuel_litres          12000 non-null  int64
 14  fuel_cost            12000 non-null  int64
 15  maintenance_type     12000 non-null  object
 16  breakdown_hours      12000 non-null  int64
 17  repair_cost          12000 non-null  int64
 18  weather              12000 non-null  object
 19  temperature_c        12000 non-null  float64
 20  blast_id             12000 non-null  object
 21  hole_depth_m         12000 non-null  float64
 22  powder_factor        12000 non-null  float64
 23  incident_type        12000 non-null  object
 24  severity             12000 non-null  object
 25  lost_days            12000 non-null  int64
 26  total_material       12000 non-null  int64
 27  production_variance  12000 non-null  int64
 28  achievement_%        12000 non-null  float64
 29  fuel_price           12000 non-null  float64
 30  month                12000 non-null  object
 31  year                 12000 non-null  int32
 32  quarter              12000 non-null  int32
 33  day                  12000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(11), object(15)
memory usage: 3.0+ MB

production_id          0
date                   0
shift                  0
bench_id               0
pit                    0
equipment_id           0
equipment_type         0
employee_id            0
employee_role          0
ore_tonnes             0
waste_tonnes           0
target_tonnes          0
actual_tonnes          0
fuel_litres            0
fuel_cost              0
maintenance_type       0
breakdown_hours        0
repair_cost            0
weather                0
temperature_c          0
blast_id               0
hole_depth_m           0
powder_factor          0
incident_type          0
severity               0
lost_days              0
total_material         0
production_variance    0
achievement_%          0
fuel_price             0
month                  0
year                   0
quarter                0
day                    0
dtype: int64

In [33]:
df["target_tonnes"] = (df["target_tonnes"] * 1.0527).round()

In [34]:
df.head(5)

,production_id,date,shift,bench_id,pit,equipment_id,equipment_type,employee_id,employee_role,ore_tonnes,...,severity,lost_days,total_material,production_variance,achievement_%,fuel_price,month,year,quarter,day
0,P00001,2025-01-01,C,B017,North Pit,EQ221,Dozer,EMP0143,Mining Engineer,2234,...,High,6,7264,28,100.386954,95.0,January,2025,1,Wednesday
1,P00002,2025-01-02,A,B014,South Pit,EQ222,Dumper,EMP0412,Mining Engineer,1928,...,None,0,7455,-91,98.794063,95.0,January,2025,1,Thursday
2,P00003,2025-01-03,A,B091,North Pit,EQ160,Drill,EMP0222,Mechanic,3398,...,Low,0,5975,238,104.148510,95.0,January,2025,1,Friday
3,P00004,2025-01-04,B,B081,North Pit,EQ201,Drill,EMP0253,Mechanic,3854,...,Medium,2,6613,148,102.289250,95.0,January,2025,1,Saturday
4,P00005,2025-01-05,B,B010,North Pit,EQ031,Loader,EMP0224,Mining Engineer,1241,...,Low,0,3466,300,109.475679,95.0,January,2025,1,Sunday

In [44]:
from sqlalchemy import create_engine, inspect

username = "postgres"
password = "Akshay1901"
host = "localhost"
port = "5432"
database = "Mine Operation Analysis"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

table_name = "mine"

# Check whether the table exists
inspector = inspect(engine)

if not inspector.has_table(table_name):
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="fail",
        index=False
    )
    print("Table created successfully.")
else:
    print("Table already exists. Nothing changed.")

Table already exists. Nothing changed.

In [45]:
df[['target_tonnes']].head()

   target_tonnes
0         7617.0
1         7944.0
2         6039.0
3         6806.0
4         3333.0

In [46]:
import numpy as np

df["explosive_type"] = None
df["burden"] = np.nan
df["spacing"] = np.nan

In [47]:
df.columns

Index(['production_id', 'date', 'shift', 'bench_id', 'pit', 'equipment_id',
       'equipment_type', 'employee_id', 'employee_role', 'ore_tonnes',
       'waste_tonnes', 'target_tonnes', 'actual_tonnes', 'fuel_litres',
       'fuel_cost', 'maintenance_type', 'breakdown_hours', 'repair_cost',
       'weather', 'temperature_c', 'blast_id', 'hole_depth_m', 'powder_factor',
       'incident_type', 'severity', 'lost_days', 'total_material',
       'production_variance', 'achievement_%', 'fuel_price', 'month', 'year',
       'quarter', 'day', 'explosive_type', 'burden', 'spacing'],
      dtype='object')

In [48]:
df.loc[df["powder_factor"] > 0.85, "explosive_type"] = "ANFO"

df.loc[
    (df["powder_factor"] >= 0.75) &
    (df["powder_factor"] <= 0.85),
    "explosive_type"
] = "Emulsion"

df.loc[df["powder_factor"] < 0.75, "explosive_type"] = "Slurry"

In [49]:
np.random.seed(42)

df.loc[df["explosive_type"] == "ANFO", "burden"] = np.random.uniform(
    3.4, 4.0,
    len(df[df["explosive_type"] == "ANFO"])
)

df.loc[df["explosive_type"] == "Emulsion", "burden"] = np.random.uniform(
    3.0, 3.5,
    len(df[df["explosive_type"] == "Emulsion"])
)

df.loc[df["explosive_type"] == "Slurry", "burden"] = np.random.uniform(
    2.8, 3.3,
    len(df[df["explosive_type"] == "Slurry"])
)

df["burden"] = df["burden"].round(2)

In [50]:
df.loc[df["explosive_type"] == "ANFO", "spacing"] = np.random.uniform(
    4.2, 5.0,
    len(df[df["explosive_type"] == "ANFO"])
)

df.loc[df["explosive_type"] == "Emulsion", "spacing"] = np.random.uniform(
    3.8, 4.5,
    len(df[df["explosive_type"] == "Emulsion"])
)

df.loc[df["explosive_type"] == "Slurry", "spacing"] = np.random.uniform(
    3.5, 4.1,
    len(df[df["explosive_type"] == "Slurry"])
)

df["spacing"] = df["spacing"].round(2)

In [51]:
df[["powder_factor", "explosive_type", "burden", "spacing"]].head(10)

   powder_factor explosive_type  burden  spacing
0           0.77       Emulsion    3.49     3.90
1           0.78       Emulsion    3.12     3.82
2           1.06           ANFO    3.62     4.72
3           1.06           ANFO    3.97     4.26
4           0.77       Emulsion    3.34     4.49
5           0.88           ANFO    3.84     4.39
6           0.91           ANFO    3.76     4.82
7           0.84       Emulsion    3.36     4.00
8           0.85       Emulsion    3.30     4.45
9           0.60         Slurry    2.90     3.92